# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/win_1/win.xci
# IP: The module: 'win' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/win_1/win_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'win'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/win_1/win.xci
# IP: The module: 'win' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/win_1/win_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'win'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
