# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/title1_1/title1.xci
# IP: The module: 'title1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/title1_1/title1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'title1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/title1_1/title1.xci
# IP: The module: 'title1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/title1_1/title1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'title1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
