# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Document/Verilog/VGA/VGA.cache/wt [current_project]
set_property parent.project_path D:/Document/Verilog/VGA/VGA.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {{e:/Keyboard Sample Code/Keyboard Sample Code/ip}} [current_project]
set_property ip_cache_permissions disable [current_project]
add_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/imports/Verilog/VGA/Pictrans/pikachu.coe
add_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/imports/Verilog/VGA/Pictrans/ball.coe
add_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/imports/Verilog/VGA/Pictrans/shadow.coe
add_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/imports/Verilog/VGA/Pictrans/pikachu_jump.coe
add_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/imports/Verilog/VGA/Pictrans/pikachu_down.coe
add_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/imports/Verilog/VGA/Pictrans/bg_texture.coe
add_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/imports/Verilog/VGA/Pictrans/title1.coe
add_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/imports/Verilog/VGA/Pictrans/title2.coe
add_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/imports/Verilog/VGA/Pictrans/bg_rp.coe
add_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/imports/Verilog/VGA/Pictrans/title3.coe
add_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/imports/Verilog/VGA/Pictrans/bg.coe
add_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/imports/Verilog/VGA/Pictrans/select1.coe
add_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/imports/Verilog/VGA/Pictrans/select2.coe
add_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/imports/Verilog/VGA/Pictrans/win.coe
add_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/imports/Verilog/VGA/Pictrans/lose.coe
add_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/imports/Verilog/VGA/Pictrans/bg_mid.coe
add_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/imports/Verilog/VGA/Pictrans/bg_low.coe
add_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/imports/Verilog/VGA/Pictrans/pole.coe
add_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/imports/Verilog/VGA/Pictrans/0.coe
add_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/imports/Verilog/VGA/Pictrans/1.coe
add_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/imports/Verilog/VGA/Pictrans/2.coe
add_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/imports/Verilog/VGA/Pictrans/3.coe
add_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/imports/Verilog/VGA/Pictrans/4.coe
add_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/imports/Verilog/VGA/Pictrans/5.coe
add_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/imports/Verilog/VGA/Pictrans/6.coe
add_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/imports/Verilog/VGA/Pictrans/7.coe
add_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/imports/Verilog/VGA/Pictrans/8.coe
add_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/imports/Verilog/VGA/Pictrans/9.coe
add_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/imports/Verilog/VGA/Pictrans/num.coe
add_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/imports/Verilog/VGA/Pictrans/crash.coe
add_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/imports/Verilog/VGA/Pictrans/pikachu_win.coe
add_files -quiet d:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/KeyboardCtrl_0/KeyboardCtrl_0.dcp
set_property used_in_implementation false [get_files d:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/KeyboardCtrl_0/KeyboardCtrl_0.dcp]
add_files -quiet D:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/ball_pixel_1/ball_pixel.dcp
set_property used_in_implementation false [get_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/ball_pixel_1/ball_pixel.dcp]
add_files -quiet D:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/pikachu_pixel_1/pikachu_pixel.dcp
set_property used_in_implementation false [get_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/pikachu_pixel_1/pikachu_pixel.dcp]
add_files -quiet D:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/shadow_pixel_1/shadow_pixel.dcp
set_property used_in_implementation false [get_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/shadow_pixel_1/shadow_pixel.dcp]
add_files -quiet D:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/pikachu_jump_pixel/pikachu_jump_pixel.dcp
set_property used_in_implementation false [get_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/pikachu_jump_pixel/pikachu_jump_pixel.dcp]
add_files -quiet D:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/pikachu_down_pixel/pikachu_down_pixel.dcp
set_property used_in_implementation false [get_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/pikachu_down_pixel/pikachu_down_pixel.dcp]
add_files -quiet D:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/menu_bg/menu_bg.dcp
set_property used_in_implementation false [get_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/menu_bg/menu_bg.dcp]
add_files -quiet D:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/title1_1/title1.dcp
set_property used_in_implementation false [get_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/title1_1/title1.dcp]
add_files -quiet D:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/bg_rp/bg_rp.dcp
set_property used_in_implementation false [get_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/bg_rp/bg_rp.dcp]
add_files -quiet D:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/title2_1/title2.dcp
set_property used_in_implementation false [get_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/title2_1/title2.dcp]
add_files -quiet D:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/title3/title3.dcp
set_property used_in_implementation false [get_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/title3/title3.dcp]
add_files -quiet D:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/select1/select1.dcp
set_property used_in_implementation false [get_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/select1/select1.dcp]
add_files -quiet D:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/select2/select2.dcp
set_property used_in_implementation false [get_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/select2/select2.dcp]
add_files -quiet D:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/bg_mid/bg_mid.dcp
set_property used_in_implementation false [get_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/bg_mid/bg_mid.dcp]
add_files -quiet D:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/bg_low_1/bg_low.dcp
set_property used_in_implementation false [get_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/bg_low_1/bg_low.dcp]
add_files -quiet D:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/bg_pole/bg_pole.dcp
set_property used_in_implementation false [get_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/bg_pole/bg_pole.dcp]
add_files -quiet D:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/num/num.dcp
set_property used_in_implementation false [get_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/num/num.dcp]
add_files -quiet D:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/crash_pixel/crash_pixel.dcp
set_property used_in_implementation false [get_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/crash_pixel/crash_pixel.dcp]
add_files -quiet D:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/win_1/win.dcp
set_property used_in_implementation false [get_files D:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/win_1/win.dcp]
read_verilog -library xil_defaultlib {
  D:/Document/Verilog/VGA/VGA.srcs/sources_1/new/op.v
  D:/Document/Verilog/VGA/VGA.srcs/sources_1/new/7seg.v
  D:/Document/Verilog/VGA/VGA.srcs/sources_1/imports/Verilog/DEMO/DEMO/demo2/vga.v
  D:/Document/Verilog/VGA/VGA.srcs/sources_1/imports/Verilog/DEMO/DEMO/demo2/mem_addr_gen.v
  D:/Document/Verilog/VGA/VGA.srcs/sources_1/imports/Verilog/DEMO/DEMO/demo2/clock_divisor.v
  D:/Document/Verilog/VGA/VGA.srcs/sources_1/new/kbd.v
  D:/Document/Verilog/VGA/VGA.srcs/sources_1/imports/new/pwm.v
  D:/Document/Verilog/VGA/VGA.srcs/sources_1/imports/new/control.v
  D:/Document/Verilog/VGA/VGA.srcs/sources_1/imports/new/music.v
  D:/Document/Verilog/VGA/VGA.srcs/sources_1/imports/Verilog/DEMO/DEMO/demo2/top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Document/Verilog/VGA/VGA.srcs/constrs_1/imports/demo2/Basys3_Master.xdc
set_property used_in_implementation false [get_files D:/Document/Verilog/VGA/VGA.srcs/constrs_1/imports/demo2/Basys3_Master.xdc]


synth_design -top top -part xc7a35tcpg236-1 -flatten_hierarchy none -directive RuntimeOptimized -fsm_extraction off


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
