# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/crash_pixel/crash_pixel.xci
# IP: The module: 'crash_pixel' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/crash_pixel/crash_pixel_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'crash_pixel'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/crash_pixel/crash_pixel.xci
# IP: The module: 'crash_pixel' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/crash_pixel/crash_pixel_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'crash_pixel'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
