# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/menu_bg/menu_bg.xci
# IP: The module: 'menu_bg' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/menu_bg/menu_bg_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'menu_bg'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/menu_bg/menu_bg.xci
# IP: The module: 'menu_bg' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Document/Verilog/VGA/VGA.srcs/sources_1/ip/menu_bg/menu_bg_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'menu_bg'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
